//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 06:44:50 PM IST 
//


package org.ieee.ltsc.lom.resource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Educational complexType is the container for the information that describes the key educational or
 * pedagogic characteristics of this learning object.  This is pedagogical informtion essential to those involved
 * in achieving a quality learning experience.  The audience for this metadata includes teachers, managers,
 * authors and learners.
 *             
 * 
 * <p>Java class for Educational.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Educational.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="interactivityType" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}InteractivityType.Type" minOccurs="0"/>
 *         &lt;element name="learningResourceType" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LearningResourceType.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="interactivityLevel" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}InteractivityLevel.Type" minOccurs="0"/>
 *         &lt;element name="semanticDensity" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}SemanticDensity.Type" minOccurs="0"/>
 *         &lt;element name="intendedEndUserRole" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}IntendedEndUserRole.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="context" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}Context.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typicalAgeRange" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="difficulty" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}Difficulty.Type" minOccurs="0"/>
 *         &lt;element name="typicalLearningTime" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}Duration.Type" minOccurs="0"/>
 *         &lt;element name="description" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" minOccurs="0"/>
 *         &lt;element name="language" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}CharacterString.Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Educational.Type", propOrder = {
    "interactivityTypesAndLearningResourceTypesAndInteractivityLevels"
})
public class EducationalType {

    @XmlElementRefs({
        @XmlElementRef(name = "language", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "context", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "typicalLearningTime", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "typicalAgeRange", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interactivityType", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "semanticDensity", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interactivityLevel", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "difficulty", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "learningResourceType", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "intendedEndUserRole", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> interactivityTypesAndLearningResourceTypesAndInteractivityLevels;

    /**
     * Gets the value of the interactivityTypesAndLearningResourceTypesAndInteractivityLevels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactivityTypesAndLearningResourceTypesAndInteractivityLevels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractivityTypesAndLearningResourceTypesAndInteractivityLevels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ContextType }{@code >}
     * {@link JAXBElement }{@code <}{@link DurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link LangStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link InteractivityTypeType }{@code >}
     * {@link JAXBElement }{@code <}{@link SemanticDensityType }{@code >}
     * {@link JAXBElement }{@code <}{@link InteractivityLevelType }{@code >}
     * {@link JAXBElement }{@code <}{@link DifficultyType }{@code >}
     * {@link JAXBElement }{@code <}{@link LearningResourceTypeType }{@code >}
     * {@link JAXBElement }{@code <}{@link IntendedEndUserRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link LangStringType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getInteractivityTypesAndLearningResourceTypesAndInteractivityLevels() {
        if (interactivityTypesAndLearningResourceTypesAndInteractivityLevels == null) {
            interactivityTypesAndLearningResourceTypesAndInteractivityLevels = new ArrayList<JAXBElement<?>>();
        }
        return this.interactivityTypesAndLearningResourceTypesAndInteractivityLevels;
    }

}
