//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 05:51:03 PM IST 
//


package com.pacificmetrics.saaif.metadata1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IrsDimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IrsDimensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IrtDimensionPurpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IrtModelType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IrtWeight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtRecodeRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IrtScore" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="IrtParam0" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam1" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam3" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam4" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam5" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam6" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam7" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam8" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IrtParam9" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IrsDimensionType", propOrder = {
    "irtDimensionPurpose",
    "irtModelType",
    "irtWeight",
    "irtRecodeRule",
    "irtScore",
    "irtParam0",
    "irtParam1",
    "irtParam2",
    "irtParam3",
    "irtParam4",
    "irtParam5",
    "irtParam6",
    "irtParam7",
    "irtParam8",
    "irtParam9"
})
public class IrsDimensionType {

    @XmlElement(name = "IrtDimensionPurpose")
    protected String irtDimensionPurpose;
    @XmlElement(name = "IrtModelType")
    protected String irtModelType;
    @XmlElement(name = "IrtWeight")
    protected Double irtWeight;
    @XmlElement(name = "IrtRecodeRule")
    protected String irtRecodeRule;
    @XmlElement(name = "IrtScore")
    protected BigInteger irtScore;
    @XmlElement(name = "IrtParam0")
    protected Double irtParam0;
    @XmlElement(name = "IrtParam1")
    protected Double irtParam1;
    @XmlElement(name = "IrtParam2")
    protected Double irtParam2;
    @XmlElement(name = "IrtParam3")
    protected Double irtParam3;
    @XmlElement(name = "IrtParam4")
    protected Double irtParam4;
    @XmlElement(name = "IrtParam5")
    protected Double irtParam5;
    @XmlElement(name = "IrtParam6")
    protected Double irtParam6;
    @XmlElement(name = "IrtParam7")
    protected Double irtParam7;
    @XmlElement(name = "IrtParam8")
    protected Double irtParam8;
    @XmlElement(name = "IrtParam9")
    protected Double irtParam9;

    /**
     * Gets the value of the irtDimensionPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrtDimensionPurpose() {
        return irtDimensionPurpose;
    }

    /**
     * Sets the value of the irtDimensionPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrtDimensionPurpose(String value) {
        this.irtDimensionPurpose = value;
    }

    /**
     * Gets the value of the irtModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrtModelType() {
        return irtModelType;
    }

    /**
     * Sets the value of the irtModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrtModelType(String value) {
        this.irtModelType = value;
    }

    /**
     * Gets the value of the irtWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtWeight() {
        return irtWeight;
    }

    /**
     * Sets the value of the irtWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtWeight(Double value) {
        this.irtWeight = value;
    }

    /**
     * Gets the value of the irtRecodeRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrtRecodeRule() {
        return irtRecodeRule;
    }

    /**
     * Sets the value of the irtRecodeRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrtRecodeRule(String value) {
        this.irtRecodeRule = value;
    }

    /**
     * Gets the value of the irtScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIrtScore() {
        return irtScore;
    }

    /**
     * Sets the value of the irtScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIrtScore(BigInteger value) {
        this.irtScore = value;
    }

    /**
     * Gets the value of the irtParam0 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam0() {
        return irtParam0;
    }

    /**
     * Sets the value of the irtParam0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam0(Double value) {
        this.irtParam0 = value;
    }

    /**
     * Gets the value of the irtParam1 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam1() {
        return irtParam1;
    }

    /**
     * Sets the value of the irtParam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam1(Double value) {
        this.irtParam1 = value;
    }

    /**
     * Gets the value of the irtParam2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam2() {
        return irtParam2;
    }

    /**
     * Sets the value of the irtParam2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam2(Double value) {
        this.irtParam2 = value;
    }

    /**
     * Gets the value of the irtParam3 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam3() {
        return irtParam3;
    }

    /**
     * Sets the value of the irtParam3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam3(Double value) {
        this.irtParam3 = value;
    }

    /**
     * Gets the value of the irtParam4 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam4() {
        return irtParam4;
    }

    /**
     * Sets the value of the irtParam4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam4(Double value) {
        this.irtParam4 = value;
    }

    /**
     * Gets the value of the irtParam5 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam5() {
        return irtParam5;
    }

    /**
     * Sets the value of the irtParam5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam5(Double value) {
        this.irtParam5 = value;
    }

    /**
     * Gets the value of the irtParam6 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam6() {
        return irtParam6;
    }

    /**
     * Sets the value of the irtParam6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam6(Double value) {
        this.irtParam6 = value;
    }

    /**
     * Gets the value of the irtParam7 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam7() {
        return irtParam7;
    }

    /**
     * Sets the value of the irtParam7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam7(Double value) {
        this.irtParam7 = value;
    }

    /**
     * Gets the value of the irtParam8 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam8() {
        return irtParam8;
    }

    /**
     * Sets the value of the irtParam8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam8(Double value) {
        this.irtParam8 = value;
    }

    /**
     * Gets the value of the irtParam9 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIrtParam9() {
        return irtParam9;
    }

    /**
     * Sets the value of the irtParam9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIrtParam9(Double value) {
        this.irtParam9 = value;
    }

}
