#!/bin/bash

YUM_HOME="/usr/local/yum/sbac-iaip/1.0"

RPM_HOME="$YUM_HOME/RPMS"
TMP_HOME="/tmp/rli/"

find . -name "*.rpm" -exec cp {} $TMP_HOME \;

mv $TMP_HOME/*.rpm $RPM_HOME/
cd $YUM_HOME; rm -rf repodata; createrepo .

