//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 03:51:28 PM IST 
//


package com.pacificmetrics.saaif.item1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * 
 *     Define the questionPart type.
 *     Rendering description for a graphic response item.
 *     
 * 
 * <p>Java class for QuestionPartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestionPartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Options" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}OptionsType"/>
 *         &lt;element name="Text" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}stringType" minOccurs="0"/>
 *         &lt;element name="ObjectMenuIcons" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}ObjectMenuIconsType" minOccurs="0"/>
 *         &lt;element name="ImageSpec" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}ImageSpecType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HotSpots" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}HotSpotsType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}positiveIntType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestionPartType", propOrder = {
    "options",
    "text",
    "objectMenuIcons",
    "imageSpec",
    "hotSpots",
    "any"
})
public class QuestionPartType {

    @XmlElement(name = "Options", required = true)
    protected OptionsType options;
    @XmlElement(name = "Text")
    protected String text;
    @XmlElement(name = "ObjectMenuIcons")
    protected ObjectMenuIconsType objectMenuIcons;
    @XmlElement(name = "ImageSpec")
    protected List<ImageSpecType> imageSpec;
    @XmlElement(name = "HotSpots")
    protected HotSpotsType hotSpots;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link OptionsType }
     *     
     */
    public OptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionsType }
     *     
     */
    public void setOptions(OptionsType value) {
        this.options = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the objectMenuIcons property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMenuIconsType }
     *     
     */
    public ObjectMenuIconsType getObjectMenuIcons() {
        return objectMenuIcons;
    }

    /**
     * Sets the value of the objectMenuIcons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMenuIconsType }
     *     
     */
    public void setObjectMenuIcons(ObjectMenuIconsType value) {
        this.objectMenuIcons = value;
    }

    /**
     * Gets the value of the imageSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageSpecType }
     * 
     * 
     */
    public List<ImageSpecType> getImageSpec() {
        if (imageSpec == null) {
            imageSpec = new ArrayList<ImageSpecType>();
        }
        return this.imageSpec;
    }

    /**
     * Gets the value of the hotSpots property.
     * 
     * @return
     *     possible object is
     *     {@link HotSpotsType }
     *     
     */
    public HotSpotsType getHotSpots() {
        return hotSpots;
    }

    /**
     * Sets the value of the hotSpots property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotSpotsType }
     *     
     */
    public void setHotSpots(HotSpotsType value) {
        this.hotSpots = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
