//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 03:51:28 PM IST 
//


package com.pacificmetrics.saaif.item1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * 
 *     Define the relatedElementInfo type.
 *     Additional accessibility information.
 *     
 * 
 * <p>Java class for relatedElementInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedElementInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="readAloud" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}readAloudType"/>
 *         &lt;element name="brailleText" type="{http://www.smarterapp.org/xsd/saaif/v1p0/assessmentitem_v1p0.xsd}brailleTextType"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedElementInfoType", propOrder = {
    "readAloud",
    "brailleText",
    "keyWordTranslation",
    "any"
})
public class RelatedElementInfoType {

    @XmlElement(required = true)
    protected ReadAloudType readAloud;
    @XmlElement(required = true)
    protected BrailleTextType brailleText;
    protected KeyWordTranslationType keyWordTranslation;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the readAloud property.
     * 
     * @return
     *     possible object is
     *     {@link ReadAloudType }
     *     
     */
    public ReadAloudType getReadAloud() {
        return readAloud;
    }

    /**
     * Sets the value of the readAloud property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadAloudType }
     *     
     */
    public void setReadAloud(ReadAloudType value) {
        this.readAloud = value;
    }

    /**
     * Gets the value of the brailleText property.
     * 
     * @return
     *     possible object is
     *     {@link BrailleTextType }
     *     
     */
    public BrailleTextType getBrailleText() {
        return brailleText;
    }

    /**
     * Sets the value of the brailleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrailleTextType }
     *     
     */
    public void setBrailleText(BrailleTextType value) {
        this.brailleText = value;
    }

    /**
     * Gets the value of the keyWordTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link KeyWordTranslationType }
     *     
     */
    public KeyWordTranslationType getKeyWordTranslation() {
        return keyWordTranslation;
    }

    /**
     * Sets the value of the keyWordTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyWordTranslationType }
     *     
     */
    public void setKeyWordTranslation(KeyWordTranslationType value) {
        this.keyWordTranslation = value;
    }

	/**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
