//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1998/Math/MathML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.w3.math.mathml;
