//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 06:44:50 PM IST 
//


package org.ieee.ltsc.lom.manifest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Relation complexType is the container for the information that defines the relationship between this 
 * learning object and other learning objects, if any.  To define multiple relationships, there may be multiple 
 * instances of this category.  If there is more than one target learning object the each object shall have a new 
 * relationship instance.
 *             
 * 
 * <p>Java class for Relation.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Relation.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="kind" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/manifest}Kind.Type" minOccurs="0"/>
 *         &lt;element name="resource" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/manifest}Resource.Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Relation.Type", propOrder = {
    "kindsAndResources"
})
public class RelationType {

    @XmlElements({
        @XmlElement(name = "kind", type = KindType.class),
        @XmlElement(name = "resource", type = ResourceType.class)
    })
    protected List<Object> kindsAndResources;

    /**
     * Gets the value of the kindsAndResources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kindsAndResources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKindsAndResources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KindType }
     * {@link ResourceType }
     * 
     * 
     */
    public List<Object> getKindsAndResources() {
        if (kindsAndResources == null) {
            kindsAndResources = new ArrayList<Object>();
        }
        return this.kindsAndResources;
    }

}
