//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 06:44:50 PM IST 
//


package org.ieee.ltsc.lom.resource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Classification complexType is the container for information which describes where this learning 
 * object falls within a particular classification system.  To define multiple classifications, there may be 
 * multiple instances of this category.
 *             
 * 
 * <p>Java class for Classification.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Classification.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="purpose" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}Purpose.Type" minOccurs="0"/>
 *         &lt;element name="taxonPath" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}TaxonPath.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" minOccurs="0"/>
 *         &lt;element name="keyword" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Classification.Type", propOrder = {
    "purposesAndTaxonPathsAndDescriptions"
})
public class ClassificationType {

    @XmlElementRefs({
        @XmlElementRef(name = "taxonPath", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "purpose", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "keyword", namespace = "http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> purposesAndTaxonPathsAndDescriptions;

    /**
     * Gets the value of the purposesAndTaxonPathsAndDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purposesAndTaxonPathsAndDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurposesAndTaxonPathsAndDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link LangStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link PurposeType }{@code >}
     * {@link JAXBElement }{@code <}{@link LangStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxonPathType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getPurposesAndTaxonPathsAndDescriptions() {
        if (purposesAndTaxonPathsAndDescriptions == null) {
            purposesAndTaxonPathsAndDescriptions = new ArrayList<JAXBElement<?>>();
        }
        return this.purposesAndTaxonPathsAndDescriptions;
    }

}
