//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 06:44:50 PM IST 
//


package org.ieee.ltsc.lom.resource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Duration abstract complexType is the container for an annotated duration.  The value space 
 * for the duration is defined as per ISO 8601:2000.
 *             
 * 
 * <p>Java class for Duration.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Duration.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="duration" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}CharacterString.Type" minOccurs="0"/>
 *         &lt;element name="description" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Duration.Type", propOrder = {
    "durationsAndDescriptions"
})
public class DurationType {

    @XmlElements({
        @XmlElement(name = "duration", type = String.class),
        @XmlElement(name = "description", type = LangStringType.class)
    })
    protected List<Object> durationsAndDescriptions;

    /**
     * Gets the value of the durationsAndDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the durationsAndDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDurationsAndDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link LangStringType }
     * 
     * 
     */
    public List<Object> getDurationsAndDescriptions() {
        if (durationsAndDescriptions == null) {
            durationsAndDescriptions = new ArrayList<Object>();
        }
        return this.durationsAndDescriptions;
    }

}
