//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 06:44:50 PM IST 
//


package org.ieee.ltsc.lom.resource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Resource complexType is the container for the information about the target learning object that this relationship references.
 *             
 * 
 * <p>Java class for Resource.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Resource.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="identifier" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}Identifier.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://ltsc.ieee.org/xsd/apipv1p0/LOM/resource}LangString.Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Resource.Type", propOrder = {
    "identifiersAndDescriptions"
})
public class ResourceType {

    @XmlElements({
        @XmlElement(name = "identifier", type = IdentifierType.class),
        @XmlElement(name = "description", type = LangStringType.class)
    })
    protected List<Object> identifiersAndDescriptions;

    /**
     * Gets the value of the identifiersAndDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiersAndDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiersAndDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * {@link LangStringType }
     * 
     * 
     */
    public List<Object> getIdentifiersAndDescriptions() {
        if (identifiersAndDescriptions == null) {
            identifiersAndDescriptions = new ArrayList<Object>();
        }
        return this.identifiersAndDescriptions;
    }

}
