//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//

package com.pacificmetrics.ims.apip.qti.item;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * The InlineChoiceInteraction complexType is the container for information
 * about an inline choice interaction. An inline choice is an inlineInteraction
 * that presents the user with a set of choices, each of which is a simple piece
 * of text. The candidate's task is to select one of the choices. Unlike the
 * choiceInteraction, the delivery engine must allow the candidate to review
 * their choice within the context of the surrounding text.
 * 
 * 
 * <p>
 * Java class for InlineChoiceInteraction.Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InlineChoiceInteraction.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}label" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}inlineChoice" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}id.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}label.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}required.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}class.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}shuffle.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}responseIdentifier.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}xmllang.InlineChoiceInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}xmlbase.InlineChoiceInteraction.Attr"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InlineChoiceInteraction.Type", propOrder = { "label",
		"inlineChoices" })
@XmlRootElement(name = "inlineChoiceInteraction")
public class InlineChoiceInteraction {

	protected Label label;
	@XmlElement(name = "inlineChoice", required = true)
	protected List<InlineChoice> inlineChoices;
	@XmlAttribute(name = "id")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	protected String id;
	@XmlAttribute(name = "label")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String labelAttribute;
	@XmlAttribute(name = "required")
	protected Boolean required;
	@XmlAttribute(name = "class")
	protected List<String> clazzs;
	@XmlAttribute(name = "shuffle")
	protected Boolean shuffle;
	@XmlAttribute(name = "responseIdentifier", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String responseIdentifier;
	@XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;
	@XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
	@XmlSchemaType(name = "anyURI")
	protected String base;

	/**
	 * Gets the value of the label property.
	 * 
	 * @return possible object is {@link Label }
	 * 
	 */
	public Label getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 * 
	 * @param value
	 *            allowed object is {@link Label }
	 * 
	 */
	public void setLabel(Label value) {
		label = value;
	}

	/**
	 * Gets the value of the inlineChoices property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the inlineChoices property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInlineChoices().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InlineChoice }
	 * 
	 * 
	 */
	public List<InlineChoice> getInlineChoices() {
		if (inlineChoices == null) {
			inlineChoices = new ArrayList<InlineChoice>();
		}
		return inlineChoices;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the labelAttribute property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabelAttribute() {
		return labelAttribute;
	}

	/**
	 * Sets the value of the labelAttribute property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabelAttribute(String value) {
		labelAttribute = value;
	}

	/**
	 * Gets the value of the required property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isRequired() {
		if (required == null) {
			return false;
		} else {
			return required;
		}
	}

	/**
	 * Sets the value of the required property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setRequired(Boolean value) {
		required = value;
	}

	/**
	 * Gets the value of the clazzs property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the clazzs property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getClazzs().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getClazzs() {
		if (clazzs == null) {
			clazzs = new ArrayList<String>();
		}
		return clazzs;
	}

	/**
	 * Gets the value of the shuffle property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isShuffle() {
		if (shuffle == null) {
			return false;
		} else {
			return shuffle;
		}
	}

	/**
	 * Sets the value of the shuffle property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setShuffle(Boolean value) {
		shuffle = value;
	}

	/**
	 * Gets the value of the responseIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResponseIdentifier() {
		return responseIdentifier;
	}

	/**
	 * Sets the value of the responseIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResponseIdentifier(String value) {
		responseIdentifier = value;
	}

	/**
	 * Gets the value of the lang property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the value of the lang property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLang(String value) {
		lang = value;
	}

	/**
	 * Gets the value of the base property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBase() {
		return base;
	}

	/**
	 * Sets the value of the base property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBase(String value) {
		base = value;
	}

}
