//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//


package com.pacificmetrics.ims.apip.qti.item;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The roundTo operator takes one sub-expression which must have single cardinality and a numerical base-type. The result is a single float with the value nearest to that of the expression's value such that when converted to a decimal string it represents the expression rounded by the specified rounding method to the specified precision. If the sub-expression is NULL, then the result is NULL. If the sub-expression is INF, then the result is INF. If the sub-expression is -INF, then the result is -INF. If the argument is NaN, then the result is NULL. When rounding to n significant figures, the deciding digit is the (n+1)th digit counting from the first non-zero digit from the left in the number. If the deciding digit is 5 or greater, the nth digit is increased by 1 and all digits to its right are discarded; if the deciding digit is less than 5, all digits to the right of the nth digit are discarded. When rounding to n decimal places, the deciding digit is the (n+1)th digit counting to the right from the decimal point. If the deciding digit is 5 or greater, the nth digit is increased by 1 and all digits to its right are discarded; if the deciding digit is less than 5, all digits to the right of the nth digit are discarded.
 *             
 * 
 * <p>Java class for RoundTo.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoundTo.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}and"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}gt"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}not"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}lt"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}gte"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}lte"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}or"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}sum"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}durationLT"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}durationGTE"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}subtract"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}divide"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}multiple"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}ordered"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}customOperator"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}random"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}numberIncorrect"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}numberCorrect"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}numberPresented"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}numberResponded"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}numberSelected"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}substring"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}equalRounded"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}null"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}delete"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}match"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}index"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}power"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}equal"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}contains"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}containerSize"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}correct"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}default"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}anyN"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}integerDivide"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}integerModulus"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}isNull"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}member"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}product"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}round"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}truncate"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}fieldValue"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}randomInteger"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}randomFloat"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}variable"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}outcomeMinimum"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}outcomeMaximum"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}testVariables"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}integerToFloat"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}inside"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}baseValue"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}patternMatch"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}mapResponsePoint"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}mapResponse"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}stringMatch"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}repeat"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}roundTo"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}lcm"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}gcd"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}min"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}max"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}mathConstant"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}statsOperator"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}mathOperator"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}figures.RoundTo.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}roundingMode.RoundTo.Attr"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoundTo.Type", propOrder = {
    "mathOperator",
    "statsOperator",
    "mathConstant",
    "max",
    "min",
    "gcd",
    "lcm",
    "roundTo",
    "repeat",
    "stringMatch",
    "mapResponse",
    "mapResponsePoint",
    "patternMatch",
    "baseValue",
    "inside",
    "integerToFloat",
    "testVariables",
    "outcomeMaximum",
    "outcomeMinimum",
    "variable",
    "randomFloat",
    "randomInteger",
    "fieldValue",
    "truncate",
    "round",
    "product",
    "member",
    "isNull",
    "integerModulus",
    "integerDivide",
    "anyN",
    "_default",
    "correct",
    "containerSize",
    "contains",
    "equal",
    "power",
    "index",
    "match",
    "delete",
    "_null",
    "equalRounded",
    "substring",
    "numberSelected",
    "numberResponded",
    "numberPresented",
    "numberCorrect",
    "numberIncorrect",
    "random",
    "customOperator",
    "ordered",
    "multiple",
    "divide",
    "subtract",
    "durationGTE",
    "durationLT",
    "sum",
    "or",
    "lte",
    "gte",
    "lt",
    "not",
    "gt",
    "and"
})
@XmlRootElement(name = "roundTo")
public class RoundTo {

    protected MathOperator mathOperator;
    protected StatsOperator statsOperator;
    protected MathConstant mathConstant;
    protected Logic1ToManyType max;
    protected Logic1ToManyType min;
    protected Logic1ToManyType gcd;
    protected Logic1ToManyType lcm;
    protected RoundTo roundTo;
    protected Repeat repeat;
    protected StringMatch stringMatch;
    protected MapResponseType mapResponse;
    protected MapResponseType mapResponsePoint;
    protected PatternMatch patternMatch;
    protected BaseValue baseValue;
    protected Inside inside;
    protected LogicSingleType integerToFloat;
    protected TestVariables testVariables;
    protected OutcomeMinMaxType outcomeMaximum;
    protected OutcomeMinMaxType outcomeMinimum;
    protected Variable variable;
    protected RandomFloat randomFloat;
    protected RandomInteger randomInteger;
    protected FieldValue fieldValue;
    protected LogicSingleType truncate;
    protected LogicSingleType round;
    protected Logic1ToManyType product;
    protected LogicPairType member;
    protected LogicSingleType isNull;
    protected LogicPairType integerModulus;
    protected LogicPairType integerDivide;
    protected AnyN anyN;
    @XmlElement(name = "default")
    protected Default _default;
    protected Correct correct;
    protected LogicSingleType containerSize;
    protected LogicPairType contains;
    protected Equal equal;
    protected LogicPairType power;
    protected Index index;
    protected LogicPairType match;
    protected LogicPairType delete;
    @XmlElement(name = "null")
    protected EmptyPrimitiveTypeType _null;
    protected EqualRounded equalRounded;
    protected Substring substring;
    protected NumberType numberSelected;
    protected NumberType numberResponded;
    protected NumberType numberPresented;
    protected NumberType numberCorrect;
    protected NumberType numberIncorrect;
    protected LogicSingleType random;
    protected CustomOperator customOperator;
    protected Logic0ToManyType ordered;
    protected Logic0ToManyType multiple;
    protected LogicPairType divide;
    protected LogicPairType subtract;
    protected LogicPairType durationGTE;
    protected LogicPairType durationLT;
    protected Sum sum;
    protected Logic1ToManyType or;
    protected LogicPairType lte;
    protected LogicPairType gte;
    protected LogicPairType lt;
    protected LogicSingleType not;
    protected LogicPairType gt;
    protected Logic1ToManyType and;
    @XmlAttribute(name = "figures", required = true)
    protected String figures;
    @XmlAttribute(name = "roundingMode", required = true)
    protected String roundingMode;

    /**
     * Gets the value of the mathOperator property.
     * 
     * @return
     *     possible object is
     *     {@link MathOperator }
     *     
     */
    public MathOperator getMathOperator() {
        return mathOperator;
    }

    /**
     * Sets the value of the mathOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathOperator }
     *     
     */
    public void setMathOperator(MathOperator value) {
        this.mathOperator = value;
    }

    /**
     * Gets the value of the statsOperator property.
     * 
     * @return
     *     possible object is
     *     {@link StatsOperator }
     *     
     */
    public StatsOperator getStatsOperator() {
        return statsOperator;
    }

    /**
     * Sets the value of the statsOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatsOperator }
     *     
     */
    public void setStatsOperator(StatsOperator value) {
        this.statsOperator = value;
    }

    /**
     * Gets the value of the mathConstant property.
     * 
     * @return
     *     possible object is
     *     {@link MathConstant }
     *     
     */
    public MathConstant getMathConstant() {
        return mathConstant;
    }

    /**
     * Sets the value of the mathConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathConstant }
     *     
     */
    public void setMathConstant(MathConstant value) {
        this.mathConstant = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setMax(Logic1ToManyType value) {
        this.max = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setMin(Logic1ToManyType value) {
        this.min = value;
    }

    /**
     * Gets the value of the gcd property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getGcd() {
        return gcd;
    }

    /**
     * Sets the value of the gcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setGcd(Logic1ToManyType value) {
        this.gcd = value;
    }

    /**
     * Gets the value of the lcm property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getLcm() {
        return lcm;
    }

    /**
     * Sets the value of the lcm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setLcm(Logic1ToManyType value) {
        this.lcm = value;
    }

    /**
     * Gets the value of the roundTo property.
     * 
     * @return
     *     possible object is
     *     {@link RoundTo }
     *     
     */
    public RoundTo getRoundTo() {
        return roundTo;
    }

    /**
     * Sets the value of the roundTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoundTo }
     *     
     */
    public void setRoundTo(RoundTo value) {
        this.roundTo = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     * @return
     *     possible object is
     *     {@link Repeat }
     *     
     */
    public Repeat getRepeat() {
        return repeat;
    }

    /**
     * Sets the value of the repeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Repeat }
     *     
     */
    public void setRepeat(Repeat value) {
        this.repeat = value;
    }

    /**
     * Gets the value of the stringMatch property.
     * 
     * @return
     *     possible object is
     *     {@link StringMatch }
     *     
     */
    public StringMatch getStringMatch() {
        return stringMatch;
    }

    /**
     * Sets the value of the stringMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringMatch }
     *     
     */
    public void setStringMatch(StringMatch value) {
        this.stringMatch = value;
    }

    /**
     * Gets the value of the mapResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MapResponseType }
     *     
     */
    public MapResponseType getMapResponse() {
        return mapResponse;
    }

    /**
     * Sets the value of the mapResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapResponseType }
     *     
     */
    public void setMapResponse(MapResponseType value) {
        this.mapResponse = value;
    }

    /**
     * Gets the value of the mapResponsePoint property.
     * 
     * @return
     *     possible object is
     *     {@link MapResponseType }
     *     
     */
    public MapResponseType getMapResponsePoint() {
        return mapResponsePoint;
    }

    /**
     * Sets the value of the mapResponsePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapResponseType }
     *     
     */
    public void setMapResponsePoint(MapResponseType value) {
        this.mapResponsePoint = value;
    }

    /**
     * Gets the value of the patternMatch property.
     * 
     * @return
     *     possible object is
     *     {@link PatternMatch }
     *     
     */
    public PatternMatch getPatternMatch() {
        return patternMatch;
    }

    /**
     * Sets the value of the patternMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatternMatch }
     *     
     */
    public void setPatternMatch(PatternMatch value) {
        this.patternMatch = value;
    }

    /**
     * Gets the value of the baseValue property.
     * 
     * @return
     *     possible object is
     *     {@link BaseValue }
     *     
     */
    public BaseValue getBaseValue() {
        return baseValue;
    }

    /**
     * Sets the value of the baseValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseValue }
     *     
     */
    public void setBaseValue(BaseValue value) {
        this.baseValue = value;
    }

    /**
     * Gets the value of the inside property.
     * 
     * @return
     *     possible object is
     *     {@link Inside }
     *     
     */
    public Inside getInside() {
        return inside;
    }

    /**
     * Sets the value of the inside property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inside }
     *     
     */
    public void setInside(Inside value) {
        this.inside = value;
    }

    /**
     * Gets the value of the integerToFloat property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getIntegerToFloat() {
        return integerToFloat;
    }

    /**
     * Sets the value of the integerToFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setIntegerToFloat(LogicSingleType value) {
        this.integerToFloat = value;
    }

    /**
     * Gets the value of the testVariables property.
     * 
     * @return
     *     possible object is
     *     {@link TestVariables }
     *     
     */
    public TestVariables getTestVariables() {
        return testVariables;
    }

    /**
     * Sets the value of the testVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestVariables }
     *     
     */
    public void setTestVariables(TestVariables value) {
        this.testVariables = value;
    }

    /**
     * Gets the value of the outcomeMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link OutcomeMinMaxType }
     *     
     */
    public OutcomeMinMaxType getOutcomeMaximum() {
        return outcomeMaximum;
    }

    /**
     * Sets the value of the outcomeMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutcomeMinMaxType }
     *     
     */
    public void setOutcomeMaximum(OutcomeMinMaxType value) {
        this.outcomeMaximum = value;
    }

    /**
     * Gets the value of the outcomeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link OutcomeMinMaxType }
     *     
     */
    public OutcomeMinMaxType getOutcomeMinimum() {
        return outcomeMinimum;
    }

    /**
     * Sets the value of the outcomeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutcomeMinMaxType }
     *     
     */
    public void setOutcomeMinimum(OutcomeMinMaxType value) {
        this.outcomeMinimum = value;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link Variable }
     *     
     */
    public Variable getVariable() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variable }
     *     
     */
    public void setVariable(Variable value) {
        this.variable = value;
    }

    /**
     * Gets the value of the randomFloat property.
     * 
     * @return
     *     possible object is
     *     {@link RandomFloat }
     *     
     */
    public RandomFloat getRandomFloat() {
        return randomFloat;
    }

    /**
     * Sets the value of the randomFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomFloat }
     *     
     */
    public void setRandomFloat(RandomFloat value) {
        this.randomFloat = value;
    }

    /**
     * Gets the value of the randomInteger property.
     * 
     * @return
     *     possible object is
     *     {@link RandomInteger }
     *     
     */
    public RandomInteger getRandomInteger() {
        return randomInteger;
    }

    /**
     * Sets the value of the randomInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomInteger }
     *     
     */
    public void setRandomInteger(RandomInteger value) {
        this.randomInteger = value;
    }

    /**
     * Gets the value of the fieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link FieldValue }
     *     
     */
    public FieldValue getFieldValue() {
        return fieldValue;
    }

    /**
     * Sets the value of the fieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldValue }
     *     
     */
    public void setFieldValue(FieldValue value) {
        this.fieldValue = value;
    }

    /**
     * Gets the value of the truncate property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getTruncate() {
        return truncate;
    }

    /**
     * Sets the value of the truncate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setTruncate(LogicSingleType value) {
        this.truncate = value;
    }

    /**
     * Gets the value of the round property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getRound() {
        return round;
    }

    /**
     * Sets the value of the round property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setRound(LogicSingleType value) {
        this.round = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setProduct(Logic1ToManyType value) {
        this.product = value;
    }

    /**
     * Gets the value of the member property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getMember() {
        return member;
    }

    /**
     * Sets the value of the member property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setMember(LogicPairType value) {
        this.member = value;
    }

    /**
     * Gets the value of the isNull property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getIsNull() {
        return isNull;
    }

    /**
     * Sets the value of the isNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setIsNull(LogicSingleType value) {
        this.isNull = value;
    }

    /**
     * Gets the value of the integerModulus property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getIntegerModulus() {
        return integerModulus;
    }

    /**
     * Sets the value of the integerModulus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setIntegerModulus(LogicPairType value) {
        this.integerModulus = value;
    }

    /**
     * Gets the value of the integerDivide property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getIntegerDivide() {
        return integerDivide;
    }

    /**
     * Sets the value of the integerDivide property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setIntegerDivide(LogicPairType value) {
        this.integerDivide = value;
    }

    /**
     * Gets the value of the anyN property.
     * 
     * @return
     *     possible object is
     *     {@link AnyN }
     *     
     */
    public AnyN getAnyN() {
        return anyN;
    }

    /**
     * Sets the value of the anyN property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyN }
     *     
     */
    public void setAnyN(AnyN value) {
        this.anyN = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link Default }
     *     
     */
    public Default getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link Default }
     *     
     */
    public void setDefault(Default value) {
        this._default = value;
    }

    /**
     * Gets the value of the correct property.
     * 
     * @return
     *     possible object is
     *     {@link Correct }
     *     
     */
    public Correct getCorrect() {
        return correct;
    }

    /**
     * Sets the value of the correct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Correct }
     *     
     */
    public void setCorrect(Correct value) {
        this.correct = value;
    }

    /**
     * Gets the value of the containerSize property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getContainerSize() {
        return containerSize;
    }

    /**
     * Sets the value of the containerSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setContainerSize(LogicSingleType value) {
        this.containerSize = value;
    }

    /**
     * Gets the value of the contains property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getContains() {
        return contains;
    }

    /**
     * Sets the value of the contains property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setContains(LogicPairType value) {
        this.contains = value;
    }

    /**
     * Gets the value of the equal property.
     * 
     * @return
     *     possible object is
     *     {@link Equal }
     *     
     */
    public Equal getEqual() {
        return equal;
    }

    /**
     * Sets the value of the equal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equal }
     *     
     */
    public void setEqual(Equal value) {
        this.equal = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setPower(LogicPairType value) {
        this.power = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Index }
     *     
     */
    public Index getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Index }
     *     
     */
    public void setIndex(Index value) {
        this.index = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setMatch(LogicPairType value) {
        this.match = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setDelete(LogicPairType value) {
        this.delete = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyPrimitiveTypeType }
     *     
     */
    public EmptyPrimitiveTypeType getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyPrimitiveTypeType }
     *     
     */
    public void setNull(EmptyPrimitiveTypeType value) {
        this._null = value;
    }

    /**
     * Gets the value of the equalRounded property.
     * 
     * @return
     *     possible object is
     *     {@link EqualRounded }
     *     
     */
    public EqualRounded getEqualRounded() {
        return equalRounded;
    }

    /**
     * Sets the value of the equalRounded property.
     * 
     * @param value
     *     allowed object is
     *     {@link EqualRounded }
     *     
     */
    public void setEqualRounded(EqualRounded value) {
        this.equalRounded = value;
    }

    /**
     * Gets the value of the substring property.
     * 
     * @return
     *     possible object is
     *     {@link Substring }
     *     
     */
    public Substring getSubstring() {
        return substring;
    }

    /**
     * Sets the value of the substring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Substring }
     *     
     */
    public void setSubstring(Substring value) {
        this.substring = value;
    }

    /**
     * Gets the value of the numberSelected property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumberSelected() {
        return numberSelected;
    }

    /**
     * Sets the value of the numberSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumberSelected(NumberType value) {
        this.numberSelected = value;
    }

    /**
     * Gets the value of the numberResponded property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumberResponded() {
        return numberResponded;
    }

    /**
     * Sets the value of the numberResponded property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumberResponded(NumberType value) {
        this.numberResponded = value;
    }

    /**
     * Gets the value of the numberPresented property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumberPresented() {
        return numberPresented;
    }

    /**
     * Sets the value of the numberPresented property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumberPresented(NumberType value) {
        this.numberPresented = value;
    }

    /**
     * Gets the value of the numberCorrect property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumberCorrect() {
        return numberCorrect;
    }

    /**
     * Sets the value of the numberCorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumberCorrect(NumberType value) {
        this.numberCorrect = value;
    }

    /**
     * Gets the value of the numberIncorrect property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumberIncorrect() {
        return numberIncorrect;
    }

    /**
     * Sets the value of the numberIncorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumberIncorrect(NumberType value) {
        this.numberIncorrect = value;
    }

    /**
     * Gets the value of the random property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getRandom() {
        return random;
    }

    /**
     * Sets the value of the random property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setRandom(LogicSingleType value) {
        this.random = value;
    }

    /**
     * Gets the value of the customOperator property.
     * 
     * @return
     *     possible object is
     *     {@link CustomOperator }
     *     
     */
    public CustomOperator getCustomOperator() {
        return customOperator;
    }

    /**
     * Sets the value of the customOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomOperator }
     *     
     */
    public void setCustomOperator(CustomOperator value) {
        this.customOperator = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link Logic0ToManyType }
     *     
     */
    public Logic0ToManyType getOrdered() {
        return ordered;
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic0ToManyType }
     *     
     */
    public void setOrdered(Logic0ToManyType value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link Logic0ToManyType }
     *     
     */
    public Logic0ToManyType getMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic0ToManyType }
     *     
     */
    public void setMultiple(Logic0ToManyType value) {
        this.multiple = value;
    }

    /**
     * Gets the value of the divide property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getDivide() {
        return divide;
    }

    /**
     * Sets the value of the divide property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setDivide(LogicPairType value) {
        this.divide = value;
    }

    /**
     * Gets the value of the subtract property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getSubtract() {
        return subtract;
    }

    /**
     * Sets the value of the subtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setSubtract(LogicPairType value) {
        this.subtract = value;
    }

    /**
     * Gets the value of the durationGTE property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getDurationGTE() {
        return durationGTE;
    }

    /**
     * Sets the value of the durationGTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setDurationGTE(LogicPairType value) {
        this.durationGTE = value;
    }

    /**
     * Gets the value of the durationLT property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getDurationLT() {
        return durationLT;
    }

    /**
     * Sets the value of the durationLT property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setDurationLT(LogicPairType value) {
        this.durationLT = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link Sum }
     *     
     */
    public Sum getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sum }
     *     
     */
    public void setSum(Sum value) {
        this.sum = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setOr(Logic1ToManyType value) {
        this.or = value;
    }

    /**
     * Gets the value of the lte property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getLte() {
        return lte;
    }

    /**
     * Sets the value of the lte property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setLte(LogicPairType value) {
        this.lte = value;
    }

    /**
     * Gets the value of the gte property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getGte() {
        return gte;
    }

    /**
     * Sets the value of the gte property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setGte(LogicPairType value) {
        this.gte = value;
    }

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getLt() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setLt(LogicPairType value) {
        this.lt = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link LogicSingleType }
     *     
     */
    public LogicSingleType getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicSingleType }
     *     
     */
    public void setNot(LogicSingleType value) {
        this.not = value;
    }

    /**
     * Gets the value of the gt property.
     * 
     * @return
     *     possible object is
     *     {@link LogicPairType }
     *     
     */
    public LogicPairType getGt() {
        return gt;
    }

    /**
     * Sets the value of the gt property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicPairType }
     *     
     */
    public void setGt(LogicPairType value) {
        this.gt = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link Logic1ToManyType }
     *     
     */
    public Logic1ToManyType getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic1ToManyType }
     *     
     */
    public void setAnd(Logic1ToManyType value) {
        this.and = value;
    }

    /**
     * Gets the value of the figures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFigures() {
        return figures;
    }

    /**
     * Sets the value of the figures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFigures(String value) {
        this.figures = value;
    }

    /**
     * Gets the value of the roundingMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundingMode() {
        return roundingMode;
    }

    /**
     * Sets the value of the roundingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundingMode(String value) {
        this.roundingMode = value;
    }

}
