//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//


package com.pacificmetrics.ims.apip.qti.item;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The TemplateElse complexType is the container for the alternative rules that are to be applied if the templateIf rules are NULL/FALSE.
 *             
 * 
 * <p>Java class for TemplateElse.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateElse.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}setTemplateValue"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}exitTemplate"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}templateCondition"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}setDefaultValue"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}setCorrectResponse"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2}templateConstraint"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateElse.Type", propOrder = {
    "setTemplateValuesAndExitTemplatesAndTemplateConditions"
})
@XmlRootElement(name = "templateElse")
public class TemplateElse {

    @XmlElementRefs({
        @XmlElementRef(name = "exitTemplate", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "setCorrectResponse", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "templateConstraint", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = TemplateConstraint.class, required = false),
        @XmlElementRef(name = "templateCondition", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = TemplateCondition.class, required = false),
        @XmlElementRef(name = "setDefaultValue", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "setTemplateValue", namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/qtiitem/imsqti_v2p2", type = JAXBElement.class, required = false)
    })
    protected List<java.lang.Object> setTemplateValuesAndExitTemplatesAndTemplateConditions;

    /**
     * Gets the value of the setTemplateValuesAndExitTemplatesAndTemplateConditions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setTemplateValuesAndExitTemplatesAndTemplateConditions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetTemplateValuesAndExitTemplatesAndTemplateConditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link EmptyPrimitiveTypeType }{@code >}
     * {@link TemplateConstraint }
     * {@link TemplateCondition }
     * {@link JAXBElement }{@code <}{@link SetValueType }{@code >}
     * {@link JAXBElement }{@code <}{@link SetValueType }{@code >}
     * {@link JAXBElement }{@code <}{@link SetValueType }{@code >}
     * 
     * 
     */
    public List<java.lang.Object> getSetTemplateValuesAndExitTemplatesAndTemplateConditions() {
        if (setTemplateValuesAndExitTemplatesAndTemplateConditions == null) {
            setTemplateValuesAndExitTemplatesAndTemplateConditions = new ArrayList<java.lang.Object>();
        }
        return this.setTemplateValuesAndExitTemplatesAndTemplateConditions;
    }

}
