//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 03:53:42 PM IST 
//


package com.pacificmetrics.saaif.wordlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *     Define the html type.
 *     The definition for the keyword.  
 *     The listType and listCode attributes define the type of definition.
 *     Use the xHTML type as the base.
 *     
 * 
 * <p>Java class for htmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="htmlType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.smarterapp.org/xsd/saaif/v1p0/wordlist_v1p0.xsd>w3xHtmlType">
 *       &lt;attGroup ref="{http://www.smarterapp.org/xsd/saaif/v1p0/wordlist_v1p0.xsd}glossTypeAndCodeAttr"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "htmlType")
public class HtmlType
    extends W3XHtmlType
{

    @XmlAttribute(name = "listType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String listType;
    @XmlAttribute(name = "listCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String listCode;

    /**
     * Gets the value of the listType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListType() {
        return listType;
    }

    /**
     * Sets the value of the listType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListType(String value) {
        this.listType = value;
    }

    /**
     * Gets the value of the listCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListCode() {
        return listCode;
    }

    /**
     * Sets the value of the listCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListCode(String value) {
        this.listCode = value;
    }

}
