//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 05:51:03 PM IST 
//


package com.pacificmetrics.saaif.metadata1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Metadata_QNAME = new QName("", "metadata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SmarterAppMetadataType }
     * 
     */
    public SmarterAppMetadataType createSmarterAppMetadataType() {
        return new SmarterAppMetadataType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link IrsDimensionType }
     * 
     */
    public IrsDimensionType createIrsDimensionType() {
        return new IrsDimensionType();
    }

    /**
     * Create an instance of {@link SmarterAppMetadataType.IrtDimension }
     * 
     */
    public SmarterAppMetadataType.IrtDimension createSmarterAppMetadataTypeIrtDimension() {
        return new SmarterAppMetadataType.IrtDimension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "metadata")
    public JAXBElement<MetadataType> createMetadata(MetadataType value) {
        return new JAXBElement<MetadataType>(_Metadata_QNAME, MetadataType.class, null, value);
    }

}
