//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//


package com.pacificmetrics.ims.apip.qti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The IncrementSI complexType is the container for the simple specification of the Protractor, using SI units, to be used with the set of APIP Items. The Protractor is defined in terms of its increment resolutions.
 *             
 * 
 * <p>Java class for IncrementSI.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncrementSI.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minorIncrement" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}RadialSIValue.Type" minOccurs="0"/>
 *         &lt;element name="majorIncrement" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}RadialSIValue.Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncrementSI.Type", propOrder = {
    "minorIncrement",
    "majorIncrement"
})
public class IncrementSIType {

    protected RadialSIValueType minorIncrement;
    @XmlElement(required = true)
    protected RadialSIValueType majorIncrement;

    /**
     * Gets the value of the minorIncrement property.
     * 
     * @return
     *     possible object is
     *     {@link RadialSIValueType }
     *     
     */
    public RadialSIValueType getMinorIncrement() {
        return minorIncrement;
    }

    /**
     * Sets the value of the minorIncrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadialSIValueType }
     *     
     */
    public void setMinorIncrement(RadialSIValueType value) {
        this.minorIncrement = value;
    }

    /**
     * Gets the value of the majorIncrement property.
     * 
     * @return
     *     possible object is
     *     {@link RadialSIValueType }
     *     
     */
    public RadialSIValueType getMajorIncrement() {
        return majorIncrement;
    }

    /**
     * Sets the value of the majorIncrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadialSIValueType }
     *     
     */
    public void setMajorIncrement(RadialSIValueType value) {
        this.majorIncrement = value;
    }

}
