//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//


package com.pacificmetrics.ims.apip.qti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The ScaffoldBehavior complexType is the container for the scaffolding. This content can take the form of audio, text and verbal materials.
 *             
 * 
 * <p>Java class for ScaffoldBehavior.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScaffoldBehavior.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audioFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}AudioFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="textString" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}LabelledString.Type" minOccurs="0"/>
 *         &lt;element name="spokenText" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}LabelledString.Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaffoldBehavior.Type", propOrder = {
    "audioFileInfo",
    "textString",
    "spokenText"
})
public class ScaffoldBehaviorType {

    protected AudioFileInfoType audioFileInfo;
    protected LabelledStringType textString;
    protected LabelledStringType spokenText;

    /**
     * Gets the value of the audioFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AudioFileInfoType }
     *     
     */
    public AudioFileInfoType getAudioFileInfo() {
        return audioFileInfo;
    }

    /**
     * Sets the value of the audioFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioFileInfoType }
     *     
     */
    public void setAudioFileInfo(AudioFileInfoType value) {
        this.audioFileInfo = value;
    }

    /**
     * Gets the value of the textString property.
     * 
     * @return
     *     possible object is
     *     {@link LabelledStringType }
     *     
     */
    public LabelledStringType getTextString() {
        return textString;
    }

    /**
     * Sets the value of the textString property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelledStringType }
     *     
     */
    public void setTextString(LabelledStringType value) {
        this.textString = value;
    }

    /**
     * Gets the value of the spokenText property.
     * 
     * @return
     *     possible object is
     *     {@link LabelledStringType }
     *     
     */
    public LabelledStringType getSpokenText() {
        return spokenText;
    }

    /**
     * Sets the value of the spokenText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelledStringType }
     *     
     */
    public void setSpokenText(LabelledStringType value) {
        this.spokenText = value;
    }

}
