//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.09 at 09:22:32 PM IST 
//


package com.pacificmetrics.ims.apip.qti;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The TextLink complexType is the container for the information that is used to identify the object in the original content that the new accessibility content is to replace.
 *             
 * 
 * <p>Java class for TextLink.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextLink.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="fullString" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}EmptyPrimitiveType.Type" minOccurs="0"/>
 *         &lt;element name="wordLink" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="characterLink" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="characterStringLink" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}CharacterStringLink.Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextLink.Type", propOrder = {
    "characterStringLink",
    "characterLink",
    "wordLink",
    "fullString"
})
public class TextLinkType {

    protected CharacterStringLinkType characterStringLink;
    protected BigInteger characterLink;
    protected BigInteger wordLink;
    protected EmptyPrimitiveTypeType fullString;

    /**
     * Gets the value of the characterStringLink property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterStringLinkType }
     *     
     */
    public CharacterStringLinkType getCharacterStringLink() {
        return characterStringLink;
    }

    /**
     * Sets the value of the characterStringLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterStringLinkType }
     *     
     */
    public void setCharacterStringLink(CharacterStringLinkType value) {
        this.characterStringLink = value;
    }

    /**
     * Gets the value of the characterLink property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharacterLink() {
        return characterLink;
    }

    /**
     * Sets the value of the characterLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharacterLink(BigInteger value) {
        this.characterLink = value;
    }

    /**
     * Gets the value of the wordLink property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWordLink() {
        return wordLink;
    }

    /**
     * Sets the value of the wordLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWordLink(BigInteger value) {
        this.wordLink = value;
    }

    /**
     * Gets the value of the fullString property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyPrimitiveTypeType }
     *     
     */
    public EmptyPrimitiveTypeType getFullString() {
        return fullString;
    }

    /**
     * Sets the value of the fullString property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyPrimitiveTypeType }
     *     
     */
    public void setFullString(EmptyPrimitiveTypeType value) {
        this.fullString = value;
    }

}
