INSERT INTO `administrator` VALUES (1,'','','System','','Super Admin','','','sbac07pacmetteams@pacificmetrics.com',1,'System1');
INSERT INTO `blooms_taxonomy` VALUES (1,'Knowledge of'),(2,'Comprehension'),(3,'Application'),(4,'Analysis'),(5,'Synthesis'),(6,'Evaluation');
INSERT INTO `content_area` VALUES (1,'Math'),(2,'ELA'),(3,'Science'),(4,'Social Studies');
INSERT INTO `dev_state` VALUES (1,'Development'),(2,'Review'),(3,'Testing'),(4,'Approved'),(5,'Released'),(6,'Suspended'),(9,'Rejected'),(11,'Retired'),(12,'Content Review'),(13,'Content Review 2'),(14,'On Hold'),(15,'Scheduled'),(16,'Query Resolution'),(17,'Copy Review'),(18,'Copy/Proof Approval'),(19,'New Art'),(20,'Fix Art'),(21,'Client Approval'),(22,'Client Approval 2'),(23,'Client Approval 3'),(24,'Copy Teacher Review'),(25,'Copy F2F Review'),(26,'Copy Final Review'),(27,'2nd Copy Review'),(28,'Supervisor Review'),(29,'Client Preview'),(30,'Customer Proof'),(40,'Content Review 1'),(41,'Item Update 1'),(42,'Committee Review'),(43,'Item Update 2'),(44,'Content Review 3'),(45,'Sensitivity Review'),(46,'External Editor Review'),(47,'Content Review 4'),(48,'Item Update 3'),(49,'Content Review 5'),(50,'Art Request Review'),(51,'Pending Art'),(52,'Ready for Art'),(53,'Proofreading'),(54,'Content Review 6'),(55,'Item Update 4'),(56,'Content Review 7'),(57,'QA Review'),(58,'Program Director Review'),(60,'Banked'),(61,'Consortium Review'),(62,'DNU Item Pool'),(63,'Fix Media'),(64,'New Media'),(65,'Query Resolution'),(66,'Data Review'),(67,'Operational Item Pool'),(68,'Post Admin Review'),(69,'QC Presentation Review'),(70,'Post Committee');
INSERT INTO `difficulty` VALUES (1,'Easy'),(2,'Medium'),(3,'Hard');
INSERT INTO `hierarchy_definition` VALUES (4874,1,'Teks',0,0,NULL,NULL,'0'),(4875,2,'Math',4874,1,'Math 101','Math 101','4874'),(4876,1,'CCS',0,0,NULL,NULL,'0'),(4877,2,'ELA',4876,1,'English Language Arts','ELA','4876'),(4878,2,'Math',4876,2,'Math','','4876'),(4879,3,'Grade 4',4877,1,'Grade 4','Grade 4','4877,4876'),(4880,3,'Grade 5',4877,2,'Grade 5','Grade 5','4877,4876'),(4881,4,'Reading-Literature',4879,1,'Reading-Literature','Reading-Literature','4879,4877,4876'),(4882,4,'Reading-Informational',4879,2,'Reading-Informational','Reading-Informational','4879,4877,4876'),(4883,5,'ELA4&amp;RL.1',4881,1,'Key Ideas and Details: Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.','ELA4.RL.1','4881,4879,4877,4876'),(4884,6,'ELA4.RL.1a',4883,1,'1. Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.','ELA4.RL.1a','4883,4881,4879,4877,4876'),(4886,2,'New Test Subject',4885,1,'Default Test Subject','','4885'),(4887,1,'Level1',0,0,NULL,NULL,'0'),(4888,5,'<html> hello world </html>',4887,1,'Content','<b>Big bold content</b>','4887'),(4889,1,'Bloom Hierarchy',0,0,NULL,NULL,'0'),(4890,2,'Bloom Test Subject',4889,1,'','','4889'),(4891,3,'Bloom Area',4890,1,'New node','New node','4890,4889'),(4892,4,'General Content',4891,1,'New node','New node','4891,4890,4889'),(4894,3,'K.1.2',4878,2,'K.1.2','K.1.2','4878,4876'),(4896,3,'K,1,2',4878,3,'K,1,2','K,1,2','4878,4876'),(4898,3,'K.1.2',4875,1,'K.1.2','K.1.2','4875,4874'),(4910,3,'K,1,2',4875,2,'K,1,2','K,1,2','4875,4874'),(4912,3,'null',4877,3,'null','','4877,4876'),(4915,3,'New child',4875,3,'New child','New child','4875,4874'),(4916,3,'New,child',4875,4,'New,child','New,child','4875,4874'),(4917,3,'Lab 1',4875,5,'Lab 1','Lab 1','4875,4874'),(4918,3,'Grade 6',4877,4,'Grade 6','Grade 6','4877,4876'),(4919,3,'Grade 7',4877,5,'Grade 7','Grade 7','4877,4876'),(4920,3,'Lab 2',4875,6,'Lab 2','Lab 2','4875,4874'),(4921,3,'SIB',4875,7,'SIB','','4875,4874'),(4922,4,'name2',4915,1,'name2','name2','4915,4875,4874'),(4923,4,'Reading-Literature',4880,1,'Reading-Literature','Reading-Literature','4880,4877,4876'),(4924,5,'ELA5&amp;RL.1',4923,1,'ELA5&amp;RL.1','ELA5&amp;RL.1','4923,4880,4877,4876');
INSERT INTO `item_type` VALUES (1,'SR, exclusive'),(2,'SR, non-exclusive'),(3,'CR, single-line'),(4,'CR, multi-line'),(5,'Bubble/Grid'),(6,'Interactive'),(23,'CR, multi-entry, single-line'),(24,'CR, multi-entry, multi-line');
INSERT INTO `languages` VALUES ('aa','Afar'),('ab','Abkhazian'),('af','Afrikaans'),('am','Amharic'),('an','Aragonese'),('ar','Arabic'),('as','Assamese'),('ay','Aymara'),('az','Azerbaijani'),('ba','Bashkir'),('be','Byelorussian (Belarusian)'),('bg','Bulgarian'),('bh','Bihari'),('bi','Bislama'),('bn','Bengali (Bangla)'),('bo','Tibetan'),('br','Breton'),('ca','Catalan'),('co','Corsican'),('cs','Czech'),('cy','Welsh'),('da','Danish'),('de','German'),('dz','Bhutani'),('el','Greek'),('en','English'),('eo','Esperanto'),('es','Spanish'),('et','Estonian'),('eu','Basque'),('fa','Farsi'),('fi','Finnish'),('fj','Fiji'),('fo','Faeroese'),('fr','French'),('fy','Frisian'),('ga','Irish'),('gd','Gaelic (Scottish)'),('gl','Galician'),('gn','Guarani'),('gu','Gujarati'),('gv','Gaelic (Manx)'),('ha','Hausa'),('he','Hebrew'),('hi','Hindi'),('hr','Croatian'),('ht','Haitian Creole'),('hu','Hungarian'),('hy','Armenian'),('ia','Interlingua'),('id','Indonesian'),('ie','Interlingue'),('ii','Sichuan Yi'),('ik','Inupiak'),('io','Ido'),('is','Icelandic'),('it','Italian'),('iu','Inuktitut'),('ja','Japanese'),('jv','Javanese'),('ka','Georgian'),('kk','Kazakh'),('kl','Greenlandic'),('km','Cambodian'),('kn','Kannada'),('ko','Korean'),('ks','Kashmiri'),('ku','Kurdish'),('ky','Kirghiz'),('la','Latin'),('li','Limburgish ( Limburger)'),('ln','Lingala'),('lo','Laothian'),('lt','Lithuanian'),('lv','Latvian (Lettish)'),('mg','Malagasy'),('mi','Maori'),('mk','Macedonian'),('ml','Malayalam'),('mn','Mongolian'),('mo','Moldavian'),('mr','Marathi'),('ms','Malay'),('mt','Maltese'),('my','Burmese'),('na','Nauru'),('ne','Nepali'),('nl','Dutch'),('no','Norwegian'),('oc','Occitan'),('om','Oromo (Afan, Galla)'),('or','Oriya'),('pa','Punjabi'),('pl','Polish'),('ps','Pashto (Pushto)'),('pt','Portuguese'),('qu','Quechua'),('rm','Rhaeto-Romance'),('rn','Kirundi (Rundi)'),('ro','Romanian'),('ru','Russian'),('rw','Kinyarwanda (Ruanda)'),('sa','Sanskrit'),('sd','Sindhi'),('sg','Sangro'),('sh','Serbo-Croatian'),('si','Sinhalese'),('sk','Slovak'),('sl','Slovenian'),('sm','Samoan'),('sn','Shona'),('so','Somali'),('sq','Albanian'),('sr','Serbian'),('ss','Siswati'),('st','Sesotho'),('su','Sundanese'),('sv','Swedish'),('sw','Swahili (Kiswahili)'),('ta','Tamil'),('te','Telugu'),('tg','Tajik'),('th','Thai'),('ti','Tigrinya'),('tk','Turkmen'),('tl','Tagalog'),('tn','Setswana'),('to','Tonga'),('tr','Turkish'),('ts','Tsonga'),('tt','Tatar'),('tw','Twi'),('ug','Uighur'),('uk','Ukrainian'),('ur','Urdu'),('uz','Uzbek'),('vi','Vietnamese'),('vo','Volapk'),('wa','Wallon'),('wo','Wolof'),('xh','Xhosa'),('yi','Yiddish'),('yo','Yoruba'),('zh','Chinese (Traditional)'),('zu','Zulu');
INSERT INTO `publication_status` VALUES (0,'Unused'),(1,'FT'),(2,'EFT'),(3,'OP'),(4,'FTA');
INSERT INTO `qualifier_label` VALUES (17,1,'Hierarchy'),(17,2,'Test Subject'),(17,3,'Area'),(17,4,'General Content'),(17,5,'Specific Content'),(17,6,'Sub-Specific Content'),(18,1,'Hierarchy'),(18,2,'Test Subject'),(18,3,'Area'),(18,4,'General Content'),(18,5,'Specific Content'),(18,6,'Sub-Specific Content'),(20,1,'Hierarchy'),(20,2,'Test Subject'),(20,3,'Area'),(20,4,'General Content'),(20,5,'Specific Content'),(20,6,'Sub-Specific Content'),(21,1,'Hierarchy'),(21,2,'Test Subject'),(21,3,'Area'),(21,4,'General Content'),(21,5,'Specific Content'),(21,6,'Sub-Specific Content');
INSERT INTO `standard_hierarchy` VALUES (18,'CCS','Common Core State Standards','The Common Core State Standard hierarchy','0000-00-00','',4876);
INSERT INTO `user` VALUES (1,NULL,'system','mtfu',11,1,'2012-09-25 23:35:52',0,NULL,208,1,1,2);

/*Data for the table `stat_administration_status` */

insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (0,'Undefined');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (1,'Success');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (2,'Partial');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (3,'Failure');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (4,'Active');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (5,'Inactive');
insert  into `stat_administration_status`(`sas_id`,`sas_name`) values (6,'Archive');

/*Data for the table `stat_key` */

insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (1,'P-Val',NULL,'float',1);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (2,'Adj P-Val',NULL,'float',1);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (3,'BIS',NULL,'float',1);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (4,'BIS Rmv',NULL,'float',1);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (5,'% Missing',NULL,'float',1);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (6,'Ext Val 1',NULL,'float',3);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (7,'Ext Val 2',NULL,'float',3);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (8,'Ext Val 3',NULL,'float',3);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (9,'Ext Val 4',NULL,'float',3);
insert  into `stat_key`(`sk_id`,`sk_name`,`sk_description`,`sk_type`,`sk_domain`) values (10,'Ext Val 5',NULL,'float',3);

INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (-1,'?');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (0,'K');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (1,'1');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (2,'2');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (3,'3');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (4,'4');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (5,'5');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (6,'6');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (7,'7');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (8,'8');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (9,'9');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (10,'10');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (11,'11');
INSERT INTO `grade_level` (`gl_id`,`gl_name`) VALUES (12,'12');
