insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Content_Area','ELA, Math','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('WER_Item_Dimension','The three dimensions of the ELA PT WER items: A; B; C. Blank for all other items','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Excluded_from_All_Analysis','AIR and CTB indicated "Do not use" (DNU) or "Do not score" (DNS) items to not include in analysis for item issues related to test delivery and scoring. Value "Y" indicates that this item was not included in Field Test analyses.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Excluded_from_IRT_Analysis','The item was excluded from IRT analyses as a result of being rejected at content data review or causing program convergence issues. Value "Y" indicates that this item was not included in IRT analyses.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Response_Type','MC4, MC5, MS5, HT, EQ, etc','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Grade','The nominal grade for which the item was written','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Student_Grade','The student grade from which the item statistics were obtained','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Maximum_Point','The maximum possible point for the item','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Sample_Size','The number of students included to calculate this set of item statistics','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Average_Item_Score','Average item score, a value between 0 and 1. The polytomous items were moderated by the maximum score point.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Total_Correlation','Item-total correlation. Biserial for dichotomous items and polyserial for polytomous items. The total/criterion score in the LOFT-delivered Field Test is the average AIS of all items taken by a student.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingA','Percentage of students selecting MC item option A','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingB','Percentage of students selecting MC item option B','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingC','Percentage of students selecting MC item option C','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingD','Percentage of students selecting MC item option D','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingE','Percentage of students selecting MC item option E','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingF','Percentage of students selecting MC item option F','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_ChoosingG','Percentage of students selecting MC item option G','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_0','Percentage of students obtaining score 0','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_1','Percentage of students obtaining score 1','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_2','Percentage of students obtaining score 2','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_3','Percentage of students obtaining score 3','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_4','Percentage of students obtaining score 4','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_5','Percentage of students obtaining score 5','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_6','Percentage of students obtaining score 6','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_7','Percentage of students obtaining score 7','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Percent_Obtaining_8','Percentage of students obtaining score 8','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionA','Biserial for MC item option A','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionB','Biserial for MC item option B','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionC','Biserial for MC item option C','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionD','Biserial for MC item option D','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionE','Biserial for MC item option E','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionF','Biserial for MC item option F','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Biserial_OptionG','Biserial for MC item option G','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Total_Pearson_Correlation','Point-biserial for dichotomous items and point-polyserial for polytomous items. The total/criterion score in the LOFT-delivered Field Test is the average AIS of all items taken by a student.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionA','Point-biserial for MC item option A','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionB','Point-biserial for MC item option B','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionC','Point-biserial for MC item option C','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionD','Point-biserial for MC item option D','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionE','Point-biserial for MC item option E','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionF','Point-biserial for MC item option F','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Pt_biserial_OptionG','Point-biserial for MC item option G','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingA','Number of students choosing MC item option A','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionA','Mean criterion score of those students choosing option A','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_choosingB','Number of students choosing MC item option B','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionB','Mean criterion score of those students choosing option B','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingC','Number of students choosing MC item option C','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionC','Mean criterion score of those students choosing option C','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingD','Number of students choosing MC item option D','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionD','Mean criterion score of those students choosing option D','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingE','Number of students choosing MC item option E','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionE','Mean criterion score of those students choosing option E','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingF','Number of students choosing MC item option F','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionF','Mean criterion score of those students choosing option F','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_ChoosingG','Number of students choosing MC item option G','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_OptionG','Mean criterion score of those students choosing option G','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Omitting','Number of students omitting the item','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Omit','Mean criterion score of those that omitted the item','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Reached','Number of students reaching the item','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Reached','Mean criterion score of those that reached the item','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_0','Number of students obtaining the score of 0','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_0','Mean criterion score of those testers at score category 0','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_1','Number of students obtaining the score of 1','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_1','Mean criterion score of those testers at score category 1','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_2','Number of students obtaining the score of 2','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_2','Mean criterion score of those testers at score category 2','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_3','Number of students obtaining the score of 3','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_3','Mean criterion score of those testers at score category 3','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_4','Number of students obtaining the score of 4','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_4','Mean criterion score of those testers at score category 4','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_5','Number of students obtaining the score of 5','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_5','Mean criterion score of those testers at score category 5','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_6','Number of students obtaining the score of 6','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_6','Mean criterion score of those testers at score category 6','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_7','Number of students obtaining the score of 7','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_7','Mean criterion score of those testers at score category 7','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Cat_8','Number of students obtaining the score of 8','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MeanCritScore_Cat_8','Mean criterion score of those testers at score category 8','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_Female_v_Male','Female vs. Male DIF category; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_Asian_v_White','Asian vs. White DIF category;  B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_Black_v_White','Black vs. White DIF category; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_Hispanic_v_White','Hispanic vs. White DIF category; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_NativeA_v_White','Native American vs. White DIF category; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_IEP_v_NonIEP','IEP students vs. non IEP students; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_LEP_v_NonLEP','LEP students vs. non LEP students; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('DIFCat_Title1_v_NonTitle1','Title 1 eligible students vs. non eligible students; B+, B-, C+, C-','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Male','Number of male students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Female','Number of female students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_White','Number of white students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Asian','Number of Asian students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Black','Number of black students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Hispanic','Number of Hispanic students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_NativeAmerican','Number of native American students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_IEP','Number of IEP students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_LEP','Number of LEP students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('N_Title1','Number of Title 1 eligible students','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_F_M','The MH-D-DIF from the comparison of Female vs. Male students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_F_M','Standardized mean differences from the comparison of Female vs. Male students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_Asian_White','The MH-D-DIF from the comparison of Asian vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_Asian_White','Standardized mean differences from the comparison of Asian vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_Black_White','The MH-D-DIF from the comparison of Black vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_Black_White','Standardized mean differences from the comparison of Black vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_Hispanic_White','The MH-D-DIF from the comparison of Hispanic vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_Hispanic_White','Standardized mean differences from the comparison of Hispanic vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_NativeA_White','The MH-D-DIF from the comparison of Native American vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_NativeA_White','Standardized mean differences from the comparison of Native American vs. White students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_IEP_NonIEP','The MH-D-DIF from the comparison of students in Individualized Education Program (IEP) vs. non IEP students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_IEP_NonIEP','Standardized mean differences from the comparison of IEP vs. non IEP students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_LEP_NonLEP','The MH-D-DIF from the comparison of students with Limited English Proficiency (LEP) vs. non LEP students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_LEP_NonLEP','Standardized mean differences from the comparison of LEP vs. non LEP students.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('MHDDIF_Title1_NonTitle1','The MH-D-DIF from the comparison of students who are eligible or not eligible for Title 1.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('SMD_Title1_NonTitle1','Standardized mean differences from the comparison of students who are eligible or not eligible for Title 1.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_A','IRT a-parameter','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_A_SE','IRT a-parameter standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_B','IRT b-parameter','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_B_SE','IRT b-parameter standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_C','IRT c-parameter','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_C_SE','IRT c-parameter standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step1','IRT step value 1 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step1_SE','IRT step value 1 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step2','IRT step value 2 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step2_SE','IRT step value 2 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step3','IRT step value 3 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step3_SE','IRT step value 3 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step4','IRT step value 4 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step4_SE','IRT step value 4 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step5','IRT step value 5 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step5_SE','IRT step value 5 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step6','IRT step value 6 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step6_SE','IRT step value 6 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step7','IRT step value 7 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step7_SE','IRT step value 7 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step8','IRT step value 8 for polytomous items','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Step8_SE','IRT step value 8 standard error','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Fit1','Item fit statistics 1; the type of fit statistics will be determined the IRT software to be approved. The description of this field will be updated.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('IRT_Fit2','Item fit statistics 2; the type of fit statistics will be determined the IRT software to be approved.  The description of this field will be updated.','Numeric',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_A','Low Average Item Score (less than .10).','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_B','CR items with percentage obtaining any score category <3%.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_C','CR items with higher criterion score mean for students in a lower score-point category.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_D','MC items with proportionally more higher ability students select a distractor over the key.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_F','MC items with higher criterion score mean for students choosing a distractor than the mean for those choosing the key.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_H','High Average Item Score (greater than .95).','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_N','High Percent of Not Responding (Omits + Not Reached).','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_O','High Percent of Omits.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_P','MC items with positive distractor biserial correlation.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_R','Low item-total correlation (less than .30).','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_V','Smaller AIS at a higher grade level.','Character',1);
insert into stat_key(sk_name,sk_description,sk_type,sk_domain) values ('Item_Flag_Z','Flagged by statisticians as an additional item that needs content review.','Character',1);