ALTER VIEW `stat_admin_item_value_view` AS
    SELECT sai.i_id, sai.sa_id,
	(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk.sk_name = 'Content_Area') Content_Area
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'WER_Item_Dimension') WER_Item_Dimension
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Excluded_from_All_Analysis') Excluded_from_All_Analysis
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Excluded_from_IRT_Analysis') Excluded_from_IRT_Analysis
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Response_Type') Item_Response_Type
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Grade') Item_Grade
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Student_Grade') Student_Grade
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Maximum_Point') Maximum_Point
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Sample_Size') Sample_Size
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Average_Item_Score') Average_Item_Score
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Total_Correlation') Item_Total_Correlation
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingA') Percent_ChoosingA
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingB') Percent_ChoosingB
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingC') Percent_ChoosingC
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingD') Percent_ChoosingD
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingE') Percent_ChoosingE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingF') Percent_ChoosingF
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_ChoosingG') Percent_ChoosingG
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_0') Percent_Obtaining_0
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_1') Percent_Obtaining_1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_2') Percent_Obtaining_2
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_3') Percent_Obtaining_3
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_4') Percent_Obtaining_4
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_5') Percent_Obtaining_5
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_6') Percent_Obtaining_6
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_7') Percent_Obtaining_7
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Percent_Obtaining_8') Percent_Obtaining_8
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionA') Biserial_OptionA
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionB') Biserial_OptionB
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionC') Biserial_OptionC
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionD') Biserial_OptionD
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionE') Biserial_OptionE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionF') Biserial_OptionF
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Biserial_OptionG') Biserial_OptionG
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Total_Pearson_Correlation') Item_Total_Pearson_Correlation
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionA') Pt_biserial_OptionA
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionB') Pt_biserial_OptionB
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionC') Pt_biserial_OptionC
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionD') Pt_biserial_OptionD
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionE') Pt_biserial_OptionE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionF') Pt_biserial_OptionF
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Pt_biserial_OptionG') Pt_biserial_OptionG
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingA') N_ChoosingA
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionA') MeanCritScore_OptionA
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_choosingB') N_choosingB
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionB') MeanCritScore_OptionB
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingC') N_ChoosingC
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionC') MeanCritScore_OptionC
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingD') N_ChoosingD
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionD') MeanCritScore_OptionD
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingE') N_ChoosingE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionE') MeanCritScore_OptionE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingF') N_ChoosingF
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionF') MeanCritScore_OptionF
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_ChoosingG') N_ChoosingG
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_OptionG') MeanCritScore_OptionG
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Omitting') N_Omitting
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Omit') MeanCritScore_Omit
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Reached') N_Reached
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Reached') MeanCritScore_Reached
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_0') N_Cat_0
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_0') MeanCritScore_Cat_0
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_1') N_Cat_1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_1') MeanCritScore_Cat_1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_2') N_Cat_2
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_2') MeanCritScore_Cat_2
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_3') N_Cat_3
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_3') MeanCritScore_Cat_3
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_4') N_Cat_4
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_4') MeanCritScore_Cat_4
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_5') N_Cat_5
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_5') MeanCritScore_Cat_5
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_6') N_Cat_6
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_6') MeanCritScore_Cat_6
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_7') N_Cat_7
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_7') MeanCritScore_Cat_7
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Cat_8') N_Cat_8
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MeanCritScore_Cat_8') MeanCritScore_Cat_8
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_Female_v_Male') DIFCat_Female_v_Male
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_Asian_v_White') DIFCat_Asian_v_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_Black_v_White') DIFCat_Black_v_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_Hispanic_v_White') DIFCat_Hispanic_v_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_NativeA_v_White') DIFCat_NativeA_v_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_IEP_v_NonIEP') DIFCat_IEP_v_NonIEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_LEP_v_NonLEP') DIFCat_LEP_v_NonLEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'DIFCat_Title1_v_NonTitle1') DIFCat_Title1_v_NonTitle1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Male') N_Male
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Female') N_Female
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_White') N_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Asian') N_Asian
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Black') N_Black
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Hispanic') N_Hispanic
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_NativeAmerican') N_NativeAmerican
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_IEP') N_IEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_LEP') N_LEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'N_Title1') N_Title1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_F_M') MHDDIF_F_M
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_F_M') SMD_F_M
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_Asian_White') MHDDIF_Asian_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_Asian_White') SMD_Asian_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_Black_White') MHDDIF_Black_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_Black_White') SMD_Black_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_Hispanic_White') MHDDIF_Hispanic_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_Hispanic_White') SMD_Hispanic_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_NativeA_White') MHDDIF_NativeA_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_NativeA_White') SMD_NativeA_White
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_IEP_NonIEP') MHDDIF_IEP_NonIEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_IEP_NonIEP') SMD_IEP_NonIEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_LEP_NonLEP') MHDDIF_LEP_NonLEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_LEP_NonLEP') SMD_LEP_NonLEP
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'MHDDIF_Title1_NonTitle1') MHDDIF_Title1_NonTitle1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'SMD_Title1_NonTitle1') SMD_Title1_NonTitle1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_A') IRT_A
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_A_SE') IRT_A_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_B') IRT_B
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_B_SE') IRT_B_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_C') IRT_C
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_C_SE') IRT_C_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step1') IRT_Step1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step1_SE') IRT_Step1_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step2') IRT_Step2
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step2_SE') IRT_Step2_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step3') IRT_Step3
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step3_SE') IRT_Step3_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step4') IRT_Step4
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step4_SE') IRT_Step4_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step5') IRT_Step5
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step5_SE') IRT_Step5_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step6') IRT_Step6
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step6_SE') IRT_Step6_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step7') IRT_Step7
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step7_SE') IRT_Step7_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step8') IRT_Step8
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Step8_SE') IRT_Step8_SE
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Fit1') IRT_Fit1
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'IRT_Fit2') IRT_Fit2
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_A') Item_Flag_A
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_B') Item_Flag_B
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_C') Item_Flag_C
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_D') Item_Flag_D
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_F') Item_Flag_F
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_H') Item_Flag_H
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_N') Item_Flag_N
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_O') Item_Flag_O
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_P') Item_Flag_P
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_R') Item_Flag_R
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_V') Item_Flag_V
	,(SELECT siv.siv_numeric_value FROM stat_key sk, stat_item_value siv WHERE siv.i_id = sai.i_id AND siv.sa_id = sai.sa_id AND siv.sk_id = sk.sk_id AND sk_name = 'Item_Flag_Z') Item_Flag_Z
FROM stat_administration_item_view sai;
