//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 04:29:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.smarterapp.org/xsd/saaif/v1p0/machinerubric_v1p0.xsd")
package com.pacificmetrics.saaif.rubric;
